#pragma once
#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX

#define CM_QFTR_DISABLED
#define CM_QLYR_DISABLED
#define CM_QTAP_DISABLED
#define CM_QVER_DISABLED
#define CM_QRGB_DISABLED

// #define PLODAH_RGBINDICATORS_CAPS_HSV HSV_MAGENTA
// #define PLODAH_RGBINDICATORS_LAYER_INDEX1 6
#define PLODAH_RGBINDICATORS_LAYER_INDEXES { 6, 11, 12, 17, 18, 7, 10, 13, 16, 19 }
#define PLODAH_RGBINDICATORS_LAYER_HSV HSV_RED
#define PLODAH_RGBINDICATORS_LAYER_STARTING 2
// #define PLODAH_RGBINDICATORS_LAYER_BG_HSV HSV_ORANGE

#if defined(COMMUNITY_MODULE_MOUSE_JIGGLER_ENABLE)
  // #define MSJIGGLER_NOINTRO
  // #define MSJIGGLER_INTRO_TIMEOUT 1200
  // #define MSJIGGLER_PATTERN 1
  // #define MSJIGGLER_AUTOSTOP
  // #define PLODAH_RGBINDICATORS_MSJIGGLER_INDEX 20
  // #define PLODAH_RGBINDICATORS_MSJIGGLER_HSV 0x0B, 0xFF, 0xFF
#endif // COMMUNITY_MODULE_MOUSE_JIGGLER_ENABLE

/* ------- RGB MATRIX ------- */
#ifdef RGB_MATRIX_ENABLE
  #include "configs/rgbmatrix-effects-none.h"
  // #define PLODAH_REPEATHOLD_RATE 100
#endif // RGB_MATRIX_ENABLE

/* ------- RGB LIGHTING ------- */
#ifdef RGBLIGHT_ENABLE
  #include "configs/rgblight-effects-none.h"
#endif // RGBLIGHT_ENABLE

#include "plodah.h"
