#pragma once

// #define PLODAH_CAPS_INDIC_RGB RGB_MAGENTA
// #define PLODAH_LAYER_INDIC_INDEX1 6
// #define PLODAH_LAYER_INDIC_RGB RGB_MAGENTA
// #define PLODAH_LAYER_INDIC_ONZERO
// #define PLODAH_LAYER_INDIC_BG_RGB RGB_ORANGE

#define ENABLE_COMPILE_KEYCODE

#define PLODAH_ALT_TAB_DELAY 750
