#pragma once

#define PLODAH_MODS_ON_KNOB
#define PLODAH_BORING_LAYER 1

#define PLODAH_CAPS_INDIC_RGB RGB_MAGENTA

#define PLODAH_MODS_INDIC_LALT_INDEX 60
#define PLODAH_MODS_INDIC_LCTL_INDEX 58
#define PLODAH_MODS_INDIC_LSHIFT_INDEX 44
#define PLODAH_MODS_INDIC_RALT_INDEX 62
#define PLODAH_MODS_INDIC_RCTL_INDEX 64
#define PLODAH_MODS_INDIC_RSHIFT_INDEX 56
#define PLODAH_MODS_INDIC_RGB 0xAB, 0xAB, 0xFF

#define PLODAH_LAYER_INDIC_INDEX1 0
#define PLODAH_LAYER_INDIC_RGB RGB_MAGENTA
// #define PLODAH_LAYER_INDIC_ONZERO
// #define PLODAH_LAYER_INDIC_BG_RGB RGB_ORANGE

#define ENABLE_COMPILE_KEYCODE

#define PLODAH_ALT_TAB_DELAY 750

#ifdef DYNAMIC_KEYMAP_LAYER_COUNT
#undef DYNAMIC_KEYMAP_LAYER_COUNT
#endif
#define DYNAMIC_KEYMAP_LAYER_COUNT 5

#define BOOTMAGIC_ROW 0
#define BOOTMAGIC_COLUMN 0

#define DEBOUNCE 20

#define TAPPING_TERM 180
#define TAPPING_TOGGLE 3
#define TAP_CODE_DELAY 12
#define PERMISSIVE_HOLD 3

#if defined (DIP_SWITCH_ENABLE) && defined (PLODAH_BORING_LAYER)
#define dip_switch_update_kb plodah_dip_switch_update_kb
#endif

#if defined (RGB_MATRIX_ENABLE) && defined (CAPS_LOCK_LED_INDEX)
#define rgb_matrix_indicators_advanced_kb plodah_rgb_matrix_indicators_advanced_kb
#endif

/* ------- CAPS_WORD ------- */
#ifdef CAPS_WORD_ENABLE
#  ifdef BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#    undef BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#  endif
#  define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#  ifdef DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#    undef DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#  endif
#  define CAPS_WORD_DOUBLE_TAP_SHIFT_TURNS_ON
#  ifdef CAPS_WORD_IDLE_TIMEOUT
#    undef CAPS_WORD_IDLE_TIMEOUT
#  endif
#  define CAPS_WORD_IDLE_TIMEOUT 1200
#  ifdef CAPS_WORD_INVERT_ON_SHIFT
#    undef CAPS_WORD_INVERT_ON_SHIFT
#  endif
// #  define CAPS_WORD_INVERT_ON_SHIFT
#endif

/* ------- COMBO ------- */
#ifdef COMBO_ENABLE
#  ifdef COMBO_TERM
#    undef COMBO_TERM
#  endif
#  define COMBO_TERM 35
#endif

/* ------- RGB MATRIX ------- */
#ifdef RGB_MATRIX_ENABLE

#  ifdef ENABLE_RGB_MATRIX_ALPHAS_MODS
#    undef ENABLE_RGB_MATRIX_ALPHAS_MODS
#  endif
// #  define ENABLE_RGB_MATRIX_ALPHAS_MODS

#  ifdef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#    undef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#  endif
// #  define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN

#  ifdef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#    undef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#  endif
#  define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT

#  ifdef ENABLE_RGB_MATRIX_BREATHING
#    undef ENABLE_RGB_MATRIX_BREATHING
#  endif
// #  define ENABLE_RGB_MATRIX_BREATHING

#  ifdef ENABLE_RGB_MATRIX_BAND_SAT
#    undef ENABLE_RGB_MATRIX_BAND_SAT
#  endif
// #  define ENABLE_RGB_MATRIX_BAND_SAT

#  ifdef ENABLE_RGB_MATRIX_BAND_VAL
#    undef ENABLE_RGB_MATRIX_BAND_VAL
#  endif
// #  define ENABLE_RGB_MATRIX_BAND_VAL

#  ifdef ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#    undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#  endif
// #  define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT

#  ifdef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#    undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#  endif
// #  define ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL

#  ifdef ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#    undef ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#  endif
// #  define ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT

#  ifdef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#    undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#  endif
// #  define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL

#  ifdef ENABLE_RGB_MATRIX_CYCLE_ALL
#    undef ENABLE_RGB_MATRIX_CYCLE_ALL
#  endif
// #  define ENABLE_RGB_MATRIX_CYCLE_ALL

#  ifdef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#    undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#  endif
// #  define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT

#  ifdef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#    undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#  endif
// #  define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN

#  ifdef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#    undef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#  endif
// #  define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON

#  ifdef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#    undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#  endif
// #  define ENABLE_RGB_MATRIX_CYCLE_OUT_IN

#  ifdef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#    undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#  endif
// #  define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL

#  ifdef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#    undef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#  endif
// #  define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL

#  ifdef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#    undef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#  endif
// #  define ENABLE_RGB_MATRIX_CYCLE_SPIRAL

#  ifdef ENABLE_RGB_MATRIX_DUAL_BEACON
#    undef ENABLE_RGB_MATRIX_DUAL_BEACON
#  endif
// #  define ENABLE_RGB_MATRIX_DUAL_BEACON

#  ifdef ENABLE_RGB_MATRIX_RAINBOW_BEACON
#    undef ENABLE_RGB_MATRIX_RAINBOW_BEACON
#  endif
// #  define ENABLE_RGB_MATRIX_RAINBOW_BEACON

#  ifdef ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#    undef ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#  endif
// #  define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS

#  ifdef ENABLE_RGB_MATRIX_FLOWER_BLOOMING
#    undef ENABLE_RGB_MATRIX_FLOWER_BLOOMING
#  endif
// #  define ENABLE_RGB_MATRIX_FLOWER_BLOOMING

#  ifdef ENABLE_RGB_MATRIX_RAINDROPS
#    undef ENABLE_RGB_MATRIX_RAINDROPS
#  endif
// #  define ENABLE_RGB_MATRIX_RAINDROPS

#  ifdef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#    undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#  endif
// #  define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS

#  ifdef ENABLE_RGB_MATRIX_HUE_BREATHING
#    undef ENABLE_RGB_MATRIX_HUE_BREATHING
#  endif
// #  define ENABLE_RGB_MATRIX_HUE_BREATHING

#  ifdef ENABLE_RGB_MATRIX_HUE_PENDULUM
#    undef ENABLE_RGB_MATRIX_HUE_PENDULUM
#  endif
// #  define ENABLE_RGB_MATRIX_HUE_PENDULUM

#  ifdef ENABLE_RGB_MATRIX_HUE_WAVE
#    undef ENABLE_RGB_MATRIX_HUE_WAVE
#  endif
// #  define ENABLE_RGB_MATRIX_HUE_WAVE

#  ifdef ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#    undef ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#  endif
// #  define ENABLE_RGB_MATRIX_PIXEL_FRACTAL

#  ifdef ENABLE_RGB_MATRIX_PIXEL_FLOW
#    undef ENABLE_RGB_MATRIX_PIXEL_FLOW
#  endif
// #  define ENABLE_RGB_MATRIX_PIXEL_FLOW

#  ifdef ENABLE_RGB_MATRIX_PIXEL_RAIN
#    undef ENABLE_RGB_MATRIX_PIXEL_RAIN
#  endif
// #  define ENABLE_RGB_MATRIX_PIXEL_RAIN

#  ifdef ENABLE_RGB_MATRIX_STARLIGHT
#    undef ENABLE_RGB_MATRIX_STARLIGHT
#  endif
// #  define ENABLE_RGB_MATRIX_STARLIGHT

#  ifdef ENABLE_RGB_MATRIX_STARLIGHT_DUAL_HUE
#    undef ENABLE_RGB_MATRIX_STARLIGHT_DUAL_HUE
#  endif
// #  define ENABLE_RGB_MATRIX_STARLIGHT_DUAL_HUE

#  ifdef ENABLE_RGB_MATRIX_STARLIGHT_DUAL_SAT
#    undef ENABLE_RGB_MATRIX_STARLIGHT_DUAL_SAT
#  endif
#  define ENABLE_RGB_MATRIX_STARLIGHT_DUAL_SAT

#  ifdef ENABLE_RGB_MATRIX_RIVERFLOW
#    undef ENABLE_RGB_MATRIX_RIVERFLOW
#  endif
#  define ENABLE_RGB_MATRIX_RIVERFLOW

//-- Framebuffer Effects
#  ifdef ENABLE_RGB_MATRIX_TYPING_HEATMAP
#    undef ENABLE_RGB_MATRIX_TYPING_HEATMAP
#  endif
// #  define ENABLE_RGB_MATRIX_TYPING_HEATMAP

#  ifdef ENABLE_RGB_MATRIX_DIGITAL_RAIN
#    undef ENABLE_RGB_MATRIX_DIGITAL_RAIN
#  endif
// #  define ENABLE_RGB_MATRIX_DIGITAL_RAIN

//-- Reactive Effects
#  ifdef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#    undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#  endif
// #  define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE

#  ifdef ENABLE_RGB_MATRIX_SOLID_REACTIVE
#    undef ENABLE_RGB_MATRIX_SOLID_REACTIVE
#  endif
// #  define ENABLE_RGB_MATRIX_SOLID_REACTIVE

#  ifdef ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#    undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#  endif
// #  define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE

#  ifdef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#    undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#  endif
// #  define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE

#  ifdef ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#    undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#  endif
// #  define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS

#  ifdef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#    undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#  endif
// #  define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS

#  ifdef ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#    undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#  endif
// #  define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS

#  ifdef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#    undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#  endif
// #  define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS

#  ifdef ENABLE_RGB_MATRIX_SPLASH
#    undef ENABLE_RGB_MATRIX_SPLASH
#  endif
// #  define ENABLE_RGB_MATRIX_SPLASH

#  ifdef ENABLE_RGB_MATRIX_MULTISPLASH
#    undef ENABLE_RGB_MATRIX_MULTISPLASH
#  endif
// #  define ENABLE_RGB_MATRIX_MULTISPLASH

#  ifdef ENABLE_RGB_MATRIX_SOLID_SPLASH
#    undef ENABLE_RGB_MATRIX_SOLID_SPLASH
#  endif
// #  define ENABLE_RGB_MATRIX_SOLID_SPLASH

#  ifdef ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
#    undef ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
#  endif
// #  define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH

//-- RGB SETTINGS
#  ifdef RGB_MATRIX_DEFAULT_MODE
#    undef RGB_MATRIX_DEFAULT_MODE
#  endif
#  define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_GRADIENT_LEFT_RIGHT
#  ifdef RGB_MATRIX_DEFAULT_HUE
#    undef RGB_MATRIX_DEFAULT_HUE
#  endif
#  define RGB_MATRIX_DEFAULT_HUE 79
#  ifdef RGB_MATRIX_DEFAULT_SAT
#    undef RGB_MATRIX_DEFAULT_SAT
#  endif
#  define RGB_MATRIX_DEFAULT_SAT 239
#  ifdef RGB_MATRIX_DEFAULT_VAL
#    undef RGB_MATRIX_DEFAULT_VAL
#  endif
#  define RGB_MATRIX_DEFAULT_VAL 167
#  ifdef RGB_MATRIX_DEFAULT_SPD
#    undef RGB_MATRIX_DEFAULT_SPD
#  endif
#  define RGB_MATRIX_DEFAULT_SPD 48

#  ifdef RGB_MATRIX_SLEEP
#    undef RGB_MATRIX_SLEEP
#  endif
#  define RGB_MATRIX_SLEEP
#  ifdef RGB_MATRIX_TIMEOUT
#    undef RGB_MATRIX_TIMEOUT
#  endif
#  define RGB_MATRIX_TIMEOUT 270000
#endif
