#pragma once
#ifdef BACKLIGHT_ENABLE
  #ifdef BACKLIGHT_LEVELS
    #undef BACKLIGHT_LEVELS
  #endif // BACKLIGHT_LEVELS
  #define BACKLIGHT_LEVELS 15

  #ifdef BACKLIGHT_DEFAULT_LEVEL
    #undef BACKLIGHT_DEFAULT_LEVEL
  #endif // BACKLIGHT_DEFAULT_LEVEL
  #define BACKLIGHT_DEFAULT_LEVEL 5

  #ifdef BACKLIGHT_BREATHING
    #undef BACKLIGHT_BREATHING
  #endif // BACKLIGHT_BREATHING
  // #define BACKLIGHT_BREATHING

  #ifdef BREATHING_PERIOD
    #undef BREATHING_PERIOD
  #endif // BREATHING_PERIOD
  // #define BREATHING_PERIOD 4

  #ifdef BACKLIGHT_DEFAULT_ON
    #undef BACKLIGHT_DEFAULT_ON
  #endif // BACKLIGHT_DEFAULT_ON
  // #define BACKLIGHT_DEFAULT_ON true

  #ifdef BACKLIGHT_DEFAULT_BREATHING
    #undef BACKLIGHT_DEFAULT_BREATHING
  #endif // BACKLIGHT_DEFAULT_BREATHING

  #ifndef SPLIT_KEYBOARD
    #define BACKLIGHT_DEFAULT_BREATHING
  #endif // SPLIT_KEYBOARD

#endif // BACKLIGHT_ENABLE
