#ifdef BACKLIGHT_ENABLE
  #ifdef BACKLIGHT_LEVELS
    #undef BACKLIGHT_LEVELS
  #endif // BACKLIGHT_LEVELS
  #define BACKLIGHT_LEVELS 7

  #ifdef BACKLIGHT_BREATHING
    #undef BACKLIGHT_LEVELS
  #endif // BACKLIGHT_BREATHING
  #define BACKLIGHT_BREATHING true

  #ifdef BREATHING_PERIOD3
    #undef BREATHING_PERIOD
  #endif // BREATHING_PERIOD
  #define BREATHING_PERIOD 5

  #ifdef BACKLIGHT_DEFAULT_ON
    #undef BACKLIGHT_DEFAULT_ON
  #endif // BACKLIGHT_DEFAULT_ON
  #define BACKLIGHT_DEFAULT_ON true

  #ifdef BACKLIGHT_DEFAULT_BREATHING
    #undef BACKLIGHT_DEFAULT_BREATHING
  #endif // BACKLIGHT_DEFAULT_BREATHING
  #define BACKLIGHT_DEFAULT_BREATHING false

  #ifdef BACKLIGHT_DEFAULT_LEVEL
    #undef BACKLIGHT_DEFAULT_LEVEL
  #endif // BACKLIGHT_DEFAULT_LEVEL
  #define BACKLIGHT_DEFAULT_LEVEL 2

#endif // BACKLIGHT_ENABLE
