
#define IS_MOUSE
#define PLODAH_TASKSWITCH_ENABLE
#define PLODAH_DRAGSCROLL
// #define PLODAH_MSGESTURE_ENABLE

#if defined(COMMUNITY_MODULE_MOUSE_JIGGLER_ENABLE)
  // #define MSJIGGLER_NOINTRO
  // #define MSJIGGLER_INTRO_TIMEOUT 1200
  // #define MSJIGGLER_PATTERN 1
  // #define MSJIGGLER_AUTOSTOP
  // #define MSJIGGLER_INDICATOR_RGBINDEX 43
  // #define MSJIGGLER_INDICATOR_HSV 0x0B, 0xFF, 0xFF
#endif // COMMUNITY_MODULE_MOUSE_JIGGLER_ENABLE

#if defined COMMUNITY_MODULE_CONFIG_QUERY
    // #define CM_QFTR_DISABLED
    // #define CM_QLYR_DISABLED
    // #define CM_QTAP_DISABLED
    // #define CM_QVER_DISABLED
    // #define CM_QRGB_DISABLED
#endif // COMMUNITY_MODULE_CONFIG_QUERY

#ifdef PLOOPY_SCROLL_BUTTON_DEBOUNCE
  #undef PLOOPY_SCROLL_BUTTON_DEBOUNCE
#endif
#define PLOOPY_SCROLL_BUTTON_DEBOUNCE 50

#ifdef PLOOPY_SCROLL_DEBOUNCE
  #undef PLOOPY_SCROLL_DEBOUNCE
#endif
#define PLOOPY_SCROLL_DEBOUNCE 10

#ifdef PLOOPY_IGNORE_SCROLL_CLICK
  #undef PLOOPY_IGNORE_SCROLL_CLICK
#endif
#define PLOOPY_IGNORE_SCROLL_CLICK

#ifdef PLOOPY_DPI_OPTIONS
  #undef PLOOPY_DPI_OPTIONS
#endif
#define PLOOPY_DPI_OPTIONS { 300, 433, 567, 700 }

#ifdef PLOOPY_DPI_DEFAULT
  #undef PLOOPY_DPI_DEFAULT
#endif
#define PLOOPY_DPI_DEFAULT 1

#ifdef PLOOPY_DRAGSCROLL_INVERT
  #undef PLOOPY_DRAGSCROLL_INVERT
#endif
#define PLOOPY_DRAGSCROLL_INVERT 1

#ifdef PLOOPY_DRAGSCROLL_MOMENTARY
  #undef PLOOPY_DRAGSCROLL_MOMENTARY
#endif
#define PLOOPY_DRAGSCROLL_MOMENTARY 1

#ifdef PLOOPY_DRAGSCROLL_DIVISOR_H
  #undef PLOOPY_DRAGSCROLL_DIVISOR_H
#endif
#define PLOOPY_DRAGSCROLL_DIVISOR_H 4

#ifdef PLOOPY_DRAGSCROLL_DIVISOR_V
  #undef PLOOPY_DRAGSCROLL_DIVISOR_V
#endif
#define PLOOPY_DRAGSCROLL_DIVISOR_V 4

#ifdef PLODAH_DRAGSCROLL_INVERT
  #undef PLODAH_DRAGSCROLL_INVERT
#endif
#define PLODAH_DRAGSCROLL_INVERT 1

#ifdef PLODAH_DRAGSCROLL_MOMENTARY
  #undef PLODAH_DRAGSCROLL_MOMENTARY
#endif
#define PLODAH_DRAGSCROLL_MOMENTARY 1

#ifdef PLODAH_DRAGSCROLL_DIVISOR_H
  #undef PLODAH_DRAGSCROLL_DIVISOR_H
#endif
#define PLODAH_DRAGSCROLL_DIVISOR_H 4

#ifdef PLODAH_DRAGSCROLL_DIVISOR_V
  #undef PLODAH_DRAGSCROLL_DIVISOR_V
#endif
#define PLODAH_DRAGSCROLL_DIVISOR_V 4

/* ------- RGB LIGHTING ------- */
#ifdef RGBLIGHT_ENABLE
  #include "configs/rgblight-effects-none.h"
#endif // RGBLIGHT_ENABLE
