// # RGBLIGHT:033 H:109 S:254 V:216 SP:107

#if defined(RGBLIGHT_DEFAULT_MODE)
  #undef RGBLIGHT_DEFAULT_MODE
#endif // RGBLIGHT_DEFAULT_MODE
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_STATIC_LIGHT

#if defined(RGBLIGHT_DEFAULT_HUE)
  #undef RGBLIGHT_DEFAULT_HUE
#endif // RGBLIGHT_DEFAULT_HUE
#define RGBLIGHT_DEFAULT_HUE 109

#if defined(RGBLIGHT_DEFAULT_SAT)
  #undef RGBLIGHT_DEFAULT_SAT
#endif // RGBLIGHT_DEFAULT_SAT
#define RGBLIGHT_DEFAULT_SAT 255

#if defined(RGBLIGHT_DEFAULT_VAL)
  #undef RGBLIGHT_DEFAULT_VAL
#endif // RGBLIGHT_DEFAULT_VAL
#define RGBLIGHT_DEFAULT_VAL 255

#if defined(RGBLIGHT_DEFAULT_SPD)
  #undef RGBLIGHT_DEFAULT_SPD
#endif // RGBLIGHT_DEFAULT_SPD
#define RGBLIGHT_DEFAULT_SPD 0

#if defined(RGBLIGHT_DEFAULT_ON)
  #undef RGBLIGHT_DEFAULT_ON
#endif // RGBLIGHT_DEFAULT_ON
#define RGBLIGHT_DEFAULT_ON true
