#ifdef RGBLIGHT_ENABLE

  #ifdef RGBLIGHT_EFFECT_STATIC_LIGHT
    #undef RGBLIGHT_EFFECT_STATIC_LIGHT
  #endif
  #define RGBLIGHT_EFFECT_STATIC_LIGHT

  #ifdef RGBLIGHT_EFFECT_BREATHING
    #undef RGBLIGHT_EFFECT_BREATHING
  #endif
//  #define RGBLIGHT_EFFECT_BREATHING

  #ifdef RGBLIGHT_EFFECT_RAINBOW_MOOD
    #undef RGBLIGHT_EFFECT_RAINBOW_MOOD
  #endif
//  #define RGBLIGHT_EFFECT_RAINBOW_MOOD

  #ifdef RGBLIGHT_EFFECT_RAINBOW_SWIRL
    #undef RGBLIGHT_EFFECT_RAINBOW_SWIRL
  #endif
//  #define RGBLIGHT_EFFECT_RAINBOW_SWIRL

  #ifdef RGBLIGHT_EFFECT_SNAKE
    #undef RGBLIGHT_EFFECT_SNAKE
  #endif
//  #define RGBLIGHT_EFFECT_SNAKE

  #ifdef RGBLIGHT_EFFECT_KNIGHT
    #undef RGBLIGHT_EFFECT_KNIGHT
  #endif
//  #define RGBLIGHT_EFFECT_KNIGHT

  #ifdef RGBLIGHT_EFFECT_CHRISTMAS
    #undef RGBLIGHT_EFFECT_CHRISTMAS
  #endif
//  #define RGBLIGHT_EFFECT_CHRISTMAS

  #ifdef RGBLIGHT_EFFECT_STATIC_GRADIENT
    #undef RGBLIGHT_EFFECT_STATIC_GRADIENT
  #endif
  #define RGBLIGHT_EFFECT_STATIC_GRADIENT

  #ifdef RGBLIGHT_EFFECT_RGB_TEST
    #undef RGBLIGHT_EFFECT_RGB_TEST
  #endif
//  #define RGBLIGHT_EFFECT_RGB_TEST

  #ifdef RGBLIGHT_EFFECT_ALTERNATING
    #undef RGBLIGHT_EFFECT_ALTERNATING
  #endif
//  #define RGBLIGHT_EFFECT_ALTERNATING

  #ifdef RGBLIGHT_EFFECT_TWINKLE
    #undef RGBLIGHT_EFFECT_TWINKLE
  #endif
//  #define RGBLIGHT_EFFECT_TWINKLE

#endif // RGBLIGHT_ENABLE
