#pragma once

#define ENABLE_COMPILE_KEYCODE
#define MODS_ON_KNOB
#define BORING_LAYER 1
#define LAYER_IND_GRVINDEX 1
// #define LAYER_IND_ONZERO
// #define LAYER_IND_BACKGROUND

#define ALT_TAB_DELAY 750
