#pragma once
#include "plodah.h"

#define PLODAH_ALTTAB_ENHANCEMENTS_ENABLE
#define IS_MOUSE

#ifdef PLOOPY_IGNORE_SCROLL_CLICK
#  undef PLOOPY_IGNORE_SCROLL_CLICK
#endif
#define PLOOPY_IGNORE_SCROLL_CLICK

#ifdef PLOOPY_SCROLL_DEBOUNCE
#  undef PLOOPY_SCROLL_DEBOUNCE
#endif
#define PLOOPY_SCROLL_DEBOUNCE 8

#ifdef OPT_THRES
#  undef OPT_THRES
#endif
#define OPT_THRES 896

#ifdef PLOOPY_SCROLL_BUTTON_DEBOUNCE
#  undef PLOOPY_SCROLL_BUTTON_DEBOUNCE
#endif
#define PLOOPY_SCROLL_BUTTON_DEBOUNCE 50

#ifdef PLOOPY_DPI_OPTIONS
#  undef PLOOPY_DPI_OPTIONS
#endif
#define PLOOPY_DPI_OPTIONS { 300, 450, 600, 750 }

#ifdef PLOOPY_DPI_DEFAULT
#  undef PLOOPY_DPI_DEFAULT
#endif
#define PLOOPY_DPI_DEFAULT 1

#ifdef PLOOPY_DRAGSCROLL_FIXED
#  undef PLOOPY_DRAGSCROLL_FIXED
#endif
#define PLOOPY_DRAGSCROLL_FIXED 1

#ifdef PLOOPY_DRAGSCROLL_DPI
#  undef PLOOPY_DRAGSCROLL_DPI
#endif
// #define PLOOPY_DRAGSCROLL_DPI 75

#ifdef PLOOPY_DRAGSCROLL_DIVISOR_H
#  undef PLOOPY_DRAGSCROLL_DIVISOR_H
#endif
#define PLOOPY_DRAGSCROLL_DIVISOR_H 8

#ifdef PLOOPY_DRAGSCROLL_DIVISOR_V
#  undef PLOOPY_DRAGSCROLL_DIVISOR_V
#endif
#define PLOOPY_DRAGSCROLL_DIVISOR_V 8

#ifdef PLOOPY_DRAGSCROLL_MOMENTARY
#  undef PLOOPY_DRAGSCROLL_MOMENTARY
#endif
#define PLOOPY_DRAGSCROLL_MOMENTARY 1

#ifdef PLOOPY_DRAGSCROLL_INVERT
#  undef PLOOPY_DRAGSCROLL_INVERT
#endif
#define PLOOPY_DRAGSCROLL_INVERT 1

/* ------- RGB LIGHTING ------- */
#ifdef RGBLIGHT_ENABLE
#  include "configs/rgblight-effects-none.h"
#endif // RGBLIGHT_ENABLE
