#pragma once

#include "version.h"
#include "configs/customkeys.h"

#if defined(COMMUNITY_MODULE_TASK_SWITCH_ENABLE)  && (! defined(TASKSWITCH_DELAY))
  #define TASKSWITCH_DELAY 600
#endif // defined(COMMUNITY_MODULE_TASK_SWITCH_ENABLE)  && (! defined(TASKSWITCH_DELAY))

#if defined(COMBO_ENABLE) && (! defined(COMBO_TERM))
  #define COMBO_STRICT_TIMER
  #define COMBO_TERM 25
#endif // COMBO_ENABLE

#ifndef DEBOUNCE
  #define DEBOUNCE 20
#endif // DEBOUNCE

#if defined(DYNAMIC_MACRO_ENABLE) && (! defined(PLODAH_DYNAMIC_MACRO_TIMEOUT))
  #define PLODAH_DYNAMIC_MACRO_TIMEOUT 2500
#endif // DYNAMIC_MACRO_ENABLE

#if defined(LEADER_ENABLE)
  #define LEADER_PER_KEY_TIMING
  #define LEADER_TIMEOUT 200
#endif // defined(LEADER_ENABLE)

#ifndef TAPPING_TERM
  #define TAPPING_TERM 180
#endif // TAPPING_TERM

#ifndef TAPPING_TOGGLE
  #define TAPPING_TOGGLE 3
#endif // TAPPING_TOGGLE

#ifndef TAP_CODE_DELAY
  #define TAP_CODE_DELAY 8
#endif // TAP_CODE_DELAY

// #ifndef PERMISSIVE_HOLD
//   #define PERMISSIVE_HOLD
// #endif // PERMISSIVE_HOLD

#define ENABLE_COMPILE_KEYCODE

#if defined(CAPS_WORD_ENABLE)
  #ifndef BOTH_SHIFTS_TURNS_ON_CAPS_WORD
    #define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
  #endif // BOTH_SHIFTS_TURNS_ON_CAPS_WORD

  #ifndef DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
    // #define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
  #endif // DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

  #ifndef CAPS_WORD_IDLE_TIMEOUT
    #define CAPS_WORD_IDLE_TIMEOUT 1200
  #endif // CAPS_WORD_IDLE_TIMEOUT

  #ifndef CAPS_WORD_INVERT_ON_SHIFT
    #define CAPS_WORD_INVERT_ON_SHIFT
  #endif // CAPS_WORD_INVERT_ON_SHIFT
#endif // CAPS_WORD_ENABLE
