#include QMK_KEYBOARD_H

enum keymap_keycodes {
    PL_ALTTAB = QK_USER_0,
    PL_ALTSTAB,
    PL_DRAG_SCROLL_MOMENTARY,
    PL_DRAG_SCROLL_TOGGLE,
    PL_MSJG,
    PL_QFTR,
    PL_QRGB,
    PL_QVER,
};

enum {
    TD_DRAGSCROLL,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(LT(1, KC_BTN4), LT(2, KC_BTN5), KC_BTN3, KC_BTN2, KC_BTN1, TD(TD_DRAGSCROLL)),
    [1] = LAYOUT(_______, PL_ALTSTAB, PL_ALTTAB, A(KC_F4), DPI_CONFIG, PL_DRAG_SCROLL_TOGGLE),
    [2] = LAYOUT(C(KC_F4), _______, S(C(KC_TAB)), C(KC_TAB), DPI_CONFIG, PL_DRAG_SCROLL_TOGGLE)
};
