#pragma once

#include "rgb_helpers.h"

#if ( defined(PLODAH_MODS_INDIC_LCTL_INDEX) || defined(PLODAH_MODS_INDIC_RCTL_INDEX) || defined(PLODAH_MODS_INDIC_LGUI_INDEX) || defined(PLODAH_MODS_INDIC_RGUI_INDEX) || defined(PLODAH_MODS_INDIC_LALT_INDEX) || defined(PLODAH_MODS_INDIC_RALT_INDEX) || defined(PLODAH_MODS_INDIC_LSHIFT_INDEX) || defined(PLODAH_MODS_INDIC_RSHIFT_INDEX) ) && (!defined(PLODAH_MODS_INDIC_HSV))
    #define PLODAH_MODS_INDIC_HSV HSV_WHITE
#endif // PLODAH_MODS_INDIC_HSV

#if ( (defined(PLODAH_MODS_INDIC_LGUI_INDEX) || defined(PLODAH_MODS_INDIC_RGUI_INDEX)) && defined(PLODAH_GULOCK_INDIC_ENABLE) && (!defined(PLODAH_GULOCK_INDIC_HSV)) )
    #define PLODAH_GULOCK_INDIC_HSV HSV_RED
#endif // PLODAH_GULOCK_INDIC_HSV

#if (defined(PLODAH_DMAC_INDIC_INDEX)) && (!defined(PLODAH_DMAC_INDIC_HSV))
    #define PLODAH_DMAC_INDIC_HSV HSV_RED
#endif // PLODAH_DMAC_INDIC_HSV

#if (defined(CAPS_LOCK_LED_INDEX)) && (! defined(PLODAH_CAPS_INDIC_HSV))
    #define PLODAH_CAPS_INDIC_HSV HSV_RED
#endif // PLODAH_CAPS_INDIC_HSV

#if (defined(PLODAH_LAYER_INDIC_INDEX1)) && (!defined(PLODAH_LAYER_INDIC_HSV))
    #define PLODAH_LAYER_INDIC_HSV HSV_YELLOW
#endif // PLODAH_LAYER_INDIC_HSV

#ifndef PLODAH_INDICATOR_MINVAL
    #define PLODAH_INDICATOR_MINVAL 85
#endif // PLODAH_INDICATOR_MINVAL

#if defined(COMMUNITY_MODULE_MOUSE_JIGGLER_ENABLE) && defined(MSJIGGLER_INDICATOR_RGBINDEX)
  #if !defined(MSJIGGLER_INDICATOR_HSV)
    #define MSJIGGLER_INDICATOR_HSV HSV_ORANGE
  #endif // !defined(MSJIGGLER_INDICATOR_HSV)

  #if !defined(MSJIGGLER_NOINTRO) && !defined(MSJIGGLER_INDICATOR_INTRO_HSV)
    #define MSJIGGLER_INDICATOR_INTRO_HSV HSV_MAGENTA
  #endif // !defined(MSJIGGLER_NOINTRO) && !defined(MSJIGGLER_INDICATOR_INTRO_HSV)
#endif // !defined(COMMUNITY_MODULE_MOUSE_JIGGLER_ENABLE) && defined(MSJIGGLER_INDICATOR_RGBINDEX)

#if defined(PLODAH_TYPINGINDICATOR_RGBINDEX)
    bool plodah_typingindicator_active = false;
    uint16_t plodah_typingindicator_timer = 0;

    #ifndef PLODAH_TYPINGINDICATOR_HSV
      #define PLODAH_TYPINGINDICATOR_HSV HSV_RED
    #endif //PLODAH_TYPINGINDICATOR_HSV

    #ifndef PLODAH_TYPINGINDICATOR_DURATION
      #define PLODAH_TYPINGINDICATOR_DURATION 1000
    #endif //PLODAH_TYPINGINDICATOR_DURATION
    void housekeeping_task_typing_indicator(void);
    bool process_record_typing_indicator(uint16_t keycode, keyrecord_t *record);
#endif // PLODAH_TYPINGINDICATOR_RGBINDEX
