#pragma once

#if defined COMMUNITY_MODULE_CONFIG_QUERY_ENABLE
    // #define CM_QFTR_DISABLED
    #define CM_QLYR_DISABLED
    #define CM_QTAP_DISABLED
    // #define CM_QVER_DISABLED
    // #define CM_QRGB_DISABLED
#endif // COMMUNITY_MODULE_CONFIG_QUERY_ENABLE

#define PLODAH_KNOB_ENHANCEMENTS_ENABLE
#define PLODAH_BORING_LAYER 1

#define PLODAH_CAPS_INDIC_HSV HSV_MAGENTA

#define PLODAH_MODS_INDIC_LALT_INDEX 79
#define PLODAH_MODS_INDIC_LCTL_INDEX 77
#define PLODAH_MODS_INDIC_LGUI_INDEX 78
#define PLODAH_MODS_INDIC_LSHIFT_INDEX 63
#define PLODAH_MODS_INDIC_RALT_INDEX 81
#define PLODAH_MODS_INDIC_RCTL_INDEX 84
#define PLODAH_MODS_INDIC_RGUI_INDEX 82
#define PLODAH_MODS_INDIC_RSHIFT_INDEX 75
// #define PLODAH_MODS_INDIC_HSV 240, 84, 255

#define PLODAH_LAYER_INDIC_INDEX1 16
#define PLODAH_LAYER_INDIC_HSV HSV_MAGENTA
// #define PLODAH_LAYER_INDIC_ONZERO
// #define PLODAH_LAYER_INDIC_BG_HSV HSV_ORANGE

#ifdef DYNAMIC_MACRO_ENABLE
  #define PLODAH_DMAC_INDIC_INDEX 14
  #define PLODAH_DMAC_INDIC_HSV HSV_RED
#endif

#define PLODAH_TYPINGINDICATOR_RGBINDEX 15
#define PLODAH_TYPINGINDICATOR_HSV HSV_ORANGE
// #define PLODAH_TYPINGINDICATOR_DURATION 600

/* ------- RGB MATRIX ------- */
#ifdef RGB_MATRIX_ENABLE
  #include "configs/rgbmatrix-effects-none.h"
  #define PLODAH_REPEATHOLD_RGB
  // #define PLODAH_REPEATHOLD_RATE 100
#endif // RGB_MATRIX_ENABLE

#include "plodah.h"
