#pragma once

// #define CM_QFTR_DISABLED
#define CM_QLYR_DISABLED
#define CM_QTAP_DISABLED
// #define CM_QVER_DISABLED
// #define CM_QRGB_DISABLED

#ifdef COMBO_ENABLE
  #define PLODAH_HRM_COMBOS
  #define PLODAH_BRM_COMBOS
#endif

#define PLODAH_KNOB_ENHANCEMENTS_ENABLE
#define PLODAH_BORING_LAYER 1

#ifdef QUICK_TAP_TERM
  #undef QUICK_TAP_TERM
#endif
#define QUICK_TAP_TERM 60

#define PLODAH_RGBINDICATORS_CAPS_HSV HSV_MAGENTA

// #define PLODAH_RGBINDICATORS_MOD_LALT_INDEX 61
// #define PLODAH_RGBINDICATORS_MOD_LCTL_INDEX 59
// #define PLODAH_RGBINDICATORS_MOD_LSHIFT_INDEX 44
// #define PLODAH_RGBINDICATORS_MOD_RALT_INDEX 66
// #define PLODAH_RGBINDICATORS_MOD_RCTL_INDEX 66
// #define PLODAH_RGBINDICATORS_MOD_RSHIFT_INDEX 57
// #define PLODAH_RGBINDICATORS_MODS_HSV 240, 84, 255

#define PLODAH_RGBINDICATORS_LAYER_INDEX1 20
#define PLODAH_RGBINDICATORS_LAYER_HSV HSV_MAGENTA
#define PLODAH_RGBINDICATORS_LAYER_STARTING 2
// #define PLODAH_RGBINDICATORS_LAYER_BG_HSV HSV_ORANGE

#ifdef DYNAMIC_MACRO_ENABLE
  // #define PLODAH_RGBINDICATORS_DYNMACRO_INDEX 28
  // #define PLODAH_RGBINDICATORS_DYNMACRO_HSV HSV_RED
#endif

// #define PLODAH_RGBINDICATORS_TYPING_INDEX 43
// #define PLODAH_RGBINDICATORS_TYPING_HSV 240, 84, 255
// #define PLODAH_RGBINDICATORS_TYPING_DURATION 600

/* ------- RGB MATRIX ------- */
#ifdef RGB_MATRIX_ENABLE
  #include "configs/rgbmatrix-effects-few.h"
  #include "configs/rgbmatrix-config.h"
  // #define PLODAH_REPEATHOLD_RATE 100
#endif // RGB_MATRIX_ENABLE

#include "plodah.h"
