#pragma once

#define CM_QFTR_DISABLED
#define CM_QLYR_DISABLED
#define CM_QTAP_DISABLED
#define CM_QVER_DISABLED
#define CM_QRGB_DISABLED

#ifdef COMBO_ENABLE
  #define PLODAH_HRM_COMBOS
  #define PLODAH_BRM_COMBOS
  #define PLODAH_COMBOS_LIMITED
#endif

#define PLODAH_BORING_LAYER 1
/*
#ifdef QUICK_TAP_TERM
  #undef QUICK_TAP_TERM
#endif
#define QUICK_TAP_TERM 60
*/
#define PLODAH_KNOB_ENHANCEMENTS_ENABLE
#define TASKSWITCH_FORCE_NDE
#define AUTOCORRECT_RGBFLASH_FORCE_NDE

#define PLODAH_RGBINDICATORS_CAPS_HSV HSV_MAGENTA

#define PLODAH_RGBINDICATORS_MOD_LCTL_INDEX 73
#define PLODAH_RGBINDICATORS_MOD_LGUI_INDEX 74
#define PLODAH_RGBINDICATORS_MOD_LALT_INDEX 75
#define PLODAH_RGBINDICATORS_MOD_LSHIFT_INDEX 59
#define PLODAH_RGBINDICATORS_MOD_RCTL_INDEX 79
// #define PLODAH_RGBINDICATORS_MOD_RGUI_INDEX 78
// #define PLODAH_RGBINDICATORS_MOD_RALT_INDEX 77
#define PLODAH_RGBINDICATORS_MOD_RSHIFT_INDEX 71
#define PLODAH_RGBINDICATORS_MODS_HSV 240, 84, 255
#define PLODAH_RGBINDICATORS_GUILOCK_ENABLE

#define PLODAH_RGBINDICATORS_LAYER_INDEX1 15
#define PLODAH_RGBINDICATORS_LAYER_HSV HSV_MAGENTA
#define PLODAH_RGBINDICATORS_LAYER_STARTING 2
// #define PLODAH_RGBINDICATORS_LAYER_BG_HSV HSV_ORANGE

#ifdef DYNAMIC_MACRO_ENABLE
  #define PLODAH_RGBINDICATORS_DYNMACRO_INDEX 29
  #define PLODAH_RGBINDICATORS_DYNMACRO_HSV HSV_RED
#endif

// #define PLODAH_RGBINDICATORS_TYPING_INDEX 43
// #define PLODAH_RGBINDICATORS_TYPING_HSV 240, 84, 255
// #define PLODAH_RGBINDICATORS_TYPING_DURATION 600

#if defined(COMMUNITY_MODULE_MOUSE_JIGGLER_ENABLE)
  #define MSJIGGLER_NOINTRO
  // #define MSJIGGLER_INTRO_TIMEOUT 1200
  // #define MSJIGGLER_PATTERN 1
  // #define MSJIGGLER_AUTOSTOP
  #define PLODAH_RGBINDICATORS_MSJIGGLER_INDEX 43
  #define PLODAH_RGBINDICATORS_MSJIGGLER_HSV 0x0B, 0xFF, 0xFF
  #define MSJIGGLER_LOW_RESOLUTION
#endif // COMMUNITY_MODULE_MOUSE_JIGGLER_ENABLE

/* ------- RGB MATRIX ------- */
#ifdef RGB_MATRIX_ENABLE
  #define RGB_MATRIX_TIMEOUT 270000
  #include "configs/rgbmatrix-effects-fewer.h"
  #include "configs/rgbmatrix-config.h"
  // #define PLODAH_REPEATHOLD_RATE 100
#endif // RGB_MATRIX_ENABLE

#include "plodah.h"
