#pragma once

#define PLOOPY_VIAMENUS // needs to be before common
#include "configs/ploopy-common.h"

#define PLOOPY_DRAGSCROLL_SCRLK_ENABLE

// #define PLODAH_MSGESTURE_ENABLE
#define CM_QFTR_DISABLED
#define CM_QLYR_DISABLED
#define CM_QTAP_DISABLED
// #define CM_QVER_DISABLED
#define CM_QRGB_DISABLED

#ifdef PLOOPY_DPI_OPTIONS
  #undef PLOOPY_DPI_OPTIONS
#endif
#define PLOOPY_DPI_OPTIONS { 150, 180, 210, 240, 300 }

#ifdef PLOOPY_DPI_DEFAULT
  #undef PLOOPY_DPI_DEFAULT
#endif
#define PLOOPY_DPI_DEFAULT 2

#ifdef PLOOPY_DRAGSCROLL_INVERT
  #undef PLOOPY_DRAGSCROLL_INVERT
#endif
#define PLOOPY_DRAGSCROLL_INVERT 1

#ifdef PLOOPY_DRAGSCROLL_DIVISOR_V
  #undef PLOOPY_DRAGSCROLL_DIVISOR_V
#endif
#define PLOOPY_DRAGSCROLL_DIVISOR_V 8

#ifdef PLOOPY_DRAGSCROLL_DIVISOR_H
  #undef PLOOPY_DRAGSCROLL_DIVISOR_H
#endif
#define PLOOPY_DRAGSCROLL_DIVISOR_H 8

#ifdef BETTER_DRAGSCROLL_INVERT_V
  #undef BETTER_DRAGSCROLL_INVERT_V
#endif
#define BETTER_DRAGSCROLL_INVERT_V 1

#ifdef BETTER_DRAGSCROLL_DIVISOR_V
  #undef BETTER_DRAGSCROLL_DIVISOR_V
#endif
#define BETTER_DRAGSCROLL_DIVISOR_V 8

#ifdef BETTER_DRAGSCROLL_DIVISOR_H
  #undef BETTER_DRAGSCROLL_DIVISOR_H
#endif
#define BETTER_DRAGSCROLL_DIVISOR_H 8

#include "plodah.h"
