#pragma once

// #define CM_QFTR_DISABLED
#define CM_QLYR_DISABLED
#define CM_QTAP_DISABLED
// #define CM_QVER_DISABLED
// #define CM_QRGB_DISABLED

#define PLODAH_BORING_LAYER 1

#define PLODAH_RGBINDICATORS_CAPS_HSV 240, 84, 255

#define PLODAH_RGBINDICATORS_MOD_LALT_INDEX 60   ///ALL INDICES UNCHECKED
#define PLODAH_RGBINDICATORS_MOD_LCTL_INDEX 58
#define PLODAH_RGBINDICATORS_MOD_LSHIFT_INDEX 44
#define PLODAH_RGBINDICATORS_MOD_RALT_INDEX 62
// #define PLODAH_RGBINDICATORS_MOD_RCTL_INDEX 65
#define PLODAH_RGBINDICATORS_MOD_RSHIFT_INDEX 55
#define PLODAH_RGBINDICATORS_MODS_HSV 240, 84, 255

#define PLODAH_RGBINDICATORS_LAYER_INDEX1 0
#define PLODAH_RGBINDICATORS_LAYER_HSV 240, 84, 255
#define PLODAH_RGBINDICATORS_LAYER_STARTING 2
// #define PLODAH_RGBINDICATORS_LAYER_BG_HSV HSV_ORANGE

/* ------- RGB MATRIX ------- */
#ifdef RGB_MATRIX_ENABLE
  #include "configs/rgbmatrix-effects-none.h"
#endif // RGB_MATRIX_ENABLE

/* ------- RGB LIGHTING ------- */
#ifdef RGBLIGHT_ENABLE
  #include "configs/rgblight-effects-none.h"
  // #define PLODAH_REPEATHOLD_RATE 100
#endif // RGBLIGHT_ENABLE

#include "plodah.h"
