#pragma once

#include "configs/ploopy-common.h"

#define PLODAH_DRAGSCROLL_TAPDANCE

#ifdef PRODUCT
  #undef PRODUCT
#endif // PRODUCT
#define PRODUCT "Ploopy Mouse | plodahc"

#ifdef PLOOPY_DPI_OPTIONS
  #undef PLOOPY_DPI_OPTIONS
#endif
#define PLOOPY_DPI_OPTIONS { 1000, 1200, 1500, 1800, 2100 }

#ifdef PLOOPY_DRAGSCROLL_DIVISOR_H
  #undef PLOOPY_DRAGSCROLL_DIVISOR_H
#endif
#define PLOOPY_DRAGSCROLL_DIVISOR_H 8

#ifdef PLOOPY_DRAGSCROLL_DIVISOR_V
  #undef PLOOPY_DRAGSCROLL_DIVISOR_V
#endif
#define PLOOPY_DRAGSCROLL_DIVISOR_V 8

#ifdef PLODAH_DRAGSCROLL_DIVISOR_H
  #undef PLODAH_DRAGSCROLL_DIVISOR_H
#endif
#define PLODAH_DRAGSCROLL_DIVISOR_H 8

#ifdef PLODAH_DRAGSCROLL_DIVISOR_V
  #undef PLODAH_DRAGSCROLL_DIVISOR_V
#endif
#define PLODAH_DRAGSCROLL_DIVISOR_V 8

#ifdef BOOTMAGIC_ROW
  #undef BOOTMAGIC_ROW
#endif
#define BOOTMAGIC_ROW 0
#ifdef BOOTMAGIC_COLUMN
  #undef BOOTMAGIC_COLUMN
#endif
#define BOOTMAGIC_COLUMN 4

#ifdef DYNAMIC_KEYMAP_LAYER_COUNT
  #undef DYNAMIC_KEYMAP_LAYER_COUNT
#endif
#define DYNAMIC_KEYMAP_LAYER_COUNT 4

#define TAPPING_TERM 250

#include "plodah.h"
