#pragma once

#define ENABLE_COMPILE_KEYCODE
#define BORING_LAYER 4

#define CAPS_WORD_BOTH_SHIFTS_TURNS_ON
#define CAPS_WORD_DOUBLE_TAP_SHIFT_TURNS_ON
#define CAPS_WORD_IDLE_TIMEOUT 1200
#define CAPS_WORD_INVERT_ON_SHIFT

#define COMBO_TERM 35

#define DEBOUNCE 20

#ifdef DYNAMIC_KEYMAP_LAYER_COUNT
#undef DYNAMIC_KEYMAP_LAYER_COUNT
#endif
#define DYNAMIC_KEYMAP_LAYER_COUNT 5

#define TAPPING_TERM 125
#define TAPPING_TOGGLE 3
#define PERMISSIVE_HOLD 3

