name: Build QMK firmware

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    if: github.ref == 'refs/heads/main'
    with:
      qmk_repo: plodah/qmk_firmware
      qmk_ref: mybuilds-2025-03-20

  publish:
    name: 'QMK Userspace Publish'
    uses: qmk/.github/.github/workflows/qmk_userspace_publish.yml@main
    if: github.ref == 'refs/heads/main' && always() && !cancelled()
    needs: build
