#pragma once

#if !defined(DEBUG_MATRIX_SCAN_RATE)
#define DEBUG_MATRIX_SCAN_RATE
#endif // DEBUG_MATRIX_SCAN_RATE

#if !defined(OLED_FONT_H)
  #undef OLED_FONT_H
#endif // OLED_FONT_H
#define OLED_FONT_H "glcdfont.c"
#define OLED_DISPLAY_64X128
#define AUTOCORRECT_OLED_DISPLAY_LENGTH 10
#define AUTOCORRECT_OLED_DISPLAY_COUNT 3
#define MASTER_RIGHT
#define ENCODER_DIRECTION_FLIP

#ifdef ENCODER_RESOLUTION
  #undef ENCODER_RESOLUTION
#endif //ENCODER_RESOLUTION
#define ENCODER_RESOLUTION 4

#ifdef ENCODER_RESOLUTION_RIGHT
  #undef ENCODER_RESOLUTION_RIGHT
#endif //ENCODER_RESOLUTION_RIGHT
#define ENCODER_RESOLUTION_RIGHT 4

// #define CM_QFTR_DISABLED
// #define CM_QLYR_DISABLED
// #define CM_QTAP_DISABLED
// #define CM_QVER_DISABLED
// #define CM_QRGB_DISABLED

#define LAYER_NAMES { "Qwerty", "Colemak", "Gamer", "Symbols ", "Nav", "Mouse", "RGB", "dunno?" }

#define COMBOFLOW_TERM 100

#define PLODAH_KNOB_ENHANCEMENTS_ENABLE
// #define TASKSWITCH_FORCE_NDE
#define PLODAH_BORING_LAYER _G_QWERTY

#if defined(COMMUNITY_MODULE_MOUSE_JIGGLER_ENABLE)
  // #define MSJIGGLER_NOINTRO
  // #define MSJIGGLER_INTRO_TIMEOUT 1200
  // #define MSJIGGLER_PATTERN 1
  // #define MSJIGGLER_AUTOSTOP
  #define PLODAH_RGBINDICATORS_MSJIGGLER_INDEX 43
  #define PLODAH_RGBINDICATORS_MSJIGGLER_HSV 0x0B, 0xFF, 0xFF
#endif // COMMUNITY_MODULE_MOUSE_JIGGLER_ENABLE

#if defined(TAP_DANCE_ENABLE)
  #define PLODAH_TAPDANCE_TAPHOLD_ENABLE
#endif // TAP_DANCE_ENABLE

#ifdef COMBO_ENABLE
  #define PLODAH_HRM_COMBOS
  #define PLODAH_BRM_COMBOS
#endif

#ifdef QUICK_TAP_TERM
  #undef QUICK_TAP_TERM
#endif
#define QUICK_TAP_TERM 60

#ifdef RGBLIGHT_ENABLE
  #include "configs/rgblight-effects-all.h"
  #include "configs/rgblight-config.h"
  // #define PLODAH_REPEATHOLD_RATE 100
#endif // RGBLIGHT_ENABLE

#ifdef RGB_MATRIX_ENABLE
#include "configs/rgbmatrix-effects-few.h"
#include "configs/rgbmatrix-config.h"
  // #define PLODAH_REPEATHOLD_RATE 100
#endif // RGB_MATRIX_ENABLE

#if defined(TRI_LAYER_ENABLE)
  #define PLODAH_TRILAYER_SETONE
  #define PLODAH_TRILAYER_SETONE_A _SYM
  #define PLODAH_TRILAYER_SETONE_B _NAV
  #define PLODAH_TRILAYER_SETONE_C _MSE
  #define PLODAH_TRILAYER_SETTWO
  #define PLODAH_TRILAYER_SETTWO_A _NAV
  #define PLODAH_TRILAYER_SETTWO_B _MSE
  #define PLODAH_TRILAYER_SETTWO_C _RGB
#endif // TRI_LAYER_ENABLE

#include "plodah.h"
